### ISSUE TITLE
NPE when vanilla clients connect

### ISSUE THREAD

**Issue by BrainStone** [rodel77/ModBanner#2]
When Vanilla Clients connect this exception is thrown:

```
[10:32:42] [Server thread/INFO]: [+] The_BrainStone
[10:32:42] [Netty Epoll Server IO #2/INFO] [FML]: Opening channel which already seems to have a state set. This is a vanilla connection. Handshake handler will stop now
[10:32:43] [Server thread/INFO]: [STDERR]: java.lang.NullPointerException
[10:32:43] [Server thread/INFO]: [STDERR]:      at java.util.Collections$UnmodifiableMap.<init>(Collections.java:1446)
[10:32:43] [Server thread/INFO]: [STDERR]:      at java.util.Collections.unmodifiableMap(Collections.java:1433)
[10:32:43] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.getModList(NetworkDispatcher.java:312)
[10:32:43] [Server thread/INFO]: [STDERR]:      at mx.com.rodel.modbanner.PlayerModsAPI.getPlayerMods(PlayerModsAPI.java:24)
[10:32:43] [Server thread/INFO]: [STDERR]:      at mx.com.rodel.modbanner.Main.lambda$on$0(Main.java:72)
[10:32:43] [Server thread/INFO]: [STDERR]:      at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139)
[10:32:43] [Server thread/INFO]: [STDERR]:      at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:187)
[10:32:43] [Server thread/INFO]: [STDERR]:      at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:81)
[10:32:43] [Server thread/INFO]: [STDERR]:      at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:180)
[10:32:43] [Server thread/INFO]: [STDERR]:      at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:166)
[10:32:43] [Server thread/INFO]: [STDERR]:      at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
[10:32:43] [Server thread/INFO]: [STDERR]:      at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:109)
[10:32:43] [Server thread/INFO]: [STDERR]:      at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:51)
[10:32:43] [Server thread/INFO]: [STDERR]:      at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:185)
[10:32:43] [Server thread/INFO]: [STDERR]:      at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:249)
[10:32:43] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_10_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic)
[10:32:43] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[10:32:43] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635)
[10:32:43] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591)
[10:32:43] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274)
[10:32:43] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[10:32:43] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
[10:32:43] [Server thread/INFO]: [STDERR]:      at java.lang.Thread.run(Thread.java:748)
```

- Minecraft: 1.11.2
- Sponge: spongeforge-1.11.2-2282-7.0.0-BETA-2301
- Forge: 13.20.0.2296
- Modbanner: 1.0.0

**Comment by rodel77** [comment]
Fixed your next version!

**Comment by BrainStone** [comment]
@rodel77, it's still not fixed. Same error.

**Comment by rodel77** [comment]
Refixed! And now tested
