### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by BrainStone** [rodel77/ModBanner#7]
In Minecraft 1.12 I get this exception:

```
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]: java.lang.ArrayIndexOutOfBoundsException: 1
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at mx.com.rodel.modbanner.DataFile.read(DataFile.java:17)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at mx.com.rodel.modbanner.PlayerModsAPI.setData(PlayerModsAPI.java:63)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at mx.com.rodel.modbanner.PlayerModsAPI.getPlayerMods(PlayerModsAPI.java:52)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at mx.com.rodel.modbanner.Main.lambda$on$0(Main.java:71)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:187)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:180)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:166)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:109)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:46)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:182)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:255)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_12_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:634)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:590)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:281)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:654)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
[05:16:08] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:96]:         at java.lang.Thread.run(Thread.java:748)
```

**Comment by rodel77** [comment]
Hi, currently i dont have to much time to mantain this project, but i will try to fix it, i think the problem is 1.12

**Comment by rodel77** [comment]
I will be creating new things on Sponge now, you are using SpongeVanilla or SpongeForge?

**Comment by rodel77** [comment]
Sorry for the wait time, i didn't have time to Sponge since pixelmon stopped, that error its caused from your modbanner/mod_data.txt file, if you are already interested on fix it, can you send me that file please or just delete it

**Comment by BrainStone** [comment]
Ok. Great. I don't have the old file anymore. So this can be closed.

**Comment by firefox509** [comment]
Hello, I'm running into this same issue on 1.1.5 for API 7.1, I'm running a spongeforge "vanilla" server with no client-side mods needed, and it's occurring whenever a player joins with a vanilla client. 

The file then looks like this:
player1-minecraft:1.12.2,blockdrops:1.4.0,FML:8.0.99.99,mousetweaks:2.8,schematica:1.8.0.169,inventorytweaks:1.63+release.109.220f184,appleskin:1.0.9,ingameinfoxml:2.8.2.94,waila:1.8.25,jei:4.9.1.187,custommainmenu:2.0.8,jeresources:0.8.6.28,forge:14.23.1.2594,jeiintegration:1.5.1.36,wawla:2.5.253,mcp:9.42,lunatriuscore:1.2.0.42,wailaharvestability:1.1.12,controlling:3.0.6,journeymap:1.12.2-5.6.0b1,reauth:3.6.0
player2-

After the blank entry that doesn't even record minecraft:1.12.2, It no longer adds entries for other players nor will it update the file in any way once this error occurred. Which also starts allowed banned mods through. Looks like the VanillaPlayerException isn't getting caught or something... Console is going through with player trying to join with these mods: <blank> instead of logging they're not using forge

Sorry to revive an old issue, and if this project is no longer supported sorry again!
